import type { Metadata } from 'next';
import { Inter as FontSans, Outfit } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Header from './_components/Header';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

const outfit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning
    >
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
        )}
      >
        <div className='md:px-20'>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
